services:
  app:
    build: .
    ports:
      - 8081:80
    depends_on:
      - mongo
    volumes:
      - logs:/app/logs:rw
    environment:
      - MONGO_URI=mongodb://mongo:27017/habit-tracker
      - ZIPKIN_URI=http://zipkin:9411/api/v2/spans
      - NODE_ENV=docker
      - PORT=80

  mongo:
    image: mongo:5.0
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    healthcheck:
        test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
        interval: 10s
        timeout: 2s
        retries: 5
        start_period: 5s

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - es_data:/usr/share/elasticsearch/data

  logstash:
    image: docker.elastic.co/logstash/logstash:8.17.0
    depends_on:
      - elasticsearch
    ports:
      - 5044:5044
      - 9600:9600
    volumes:
      - ./configs/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./configs/logstash.yml:/usr/share/logstash/config/logstash.yml

  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.0
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.17.0
    depends_on:
      - logstash
    volumes:
      - ./configs/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - logs:/logs:ro
    command: filebeat -e --strict.perms=false

  zipkin:
    image: openzipkin/zipkin:3.4
    container_name: zipkin
    environment:
      - STORAGE_TYPE=elasticsearch
      - ES_HOSTS=http://elasticsearch:9200
    ports:
      - "9411:9411"

volumes:
  mongo-data:
  logs:
  es_data:
