filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /logs/*.log
    fields:
      application: habit-tracker
    fields_under_root: true

output.logstash:
  hosts: ["logstash:5044"]

setup.kibana:
  host: "kibana:5601"