name: App CI

on:
  push:
    branches:
      - '*'

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Install node (version 22)
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm run lint
      - name: Test
        run: pnpm run test
      - name: Up Docker Compose
        run: docker compose up -d
      - name: Create test config
        run: echo "MONGO_URI=mongodb://localhost:27017/habit-tracker" > test/.env
      - name: Run E2E tests
        run: pnpm run test:e2e
      - name: Down Docker Compose
        run: docker compose down --volumes
        if: always()
